# Generated by Django 5.2.7 on 2025-10-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisrecord',
            options={'ordering': ['-analyzed_at']},
        ),
        migrations.AlterModelOptions(
            name='wordcount',
            options={'ordering': ['-count']},
        ),
        migrations.AlterField(
            model_name='wordcount',
            name='word',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='wordcount',
            unique_together={('word', 'sentiment')},
        ),
    ]
