# Generated by Django 5.2.7 on 2026-06-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_app', '0003_reset_legacy_word_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Feedback Analysis', max_length=120)),
                ('owner_session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('source_column', models.CharField(max_length=120)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='wordcount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sentiment_app.analysisproject'),
        ),
        migrations.AddField(
            model_name='wordcount',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_counts', to='sentiment_app.analysisproject'),
        ),
        migrations.AddConstraint(
            model_name='wordcount',
            constraint=models.UniqueConstraint(fields=('project', 'word', 'sentiment'), name='unique_project_sentiment_word'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='sentiment_app.analysisproject'),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sentiment_app.uploadbatch'),
        ),
    ]
